FROM node:16-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 8010

CMD ["nginx", "-g", "daemon off;"]


# docker buildx build --platform linux/amd64,linux/arm64 -t prasanti85/reactjs:nginx-prod -f frontend/Dockerfile.prod ./frontend --push
