version: "3"
services:
  backend:
    container_name: backend_api
    image: prasanti85/nodejs:latest
    # build: ./backend
    volumes:
      - event-backend:/app
      - ./backend:/app
      - /app/node_modules
    ports:
      - 8040:80
    networks:
      - doc-net
    command: npm run dev

  frontend:
    container_name: frontend_ui
    image: prasanti85/reactjs:dev
    pull_policy: always
    # build: ./frontend
    environment:
      REACT_APP_NODE_SERVER: localhost
      REACT_APP_NODE_SERVER1: backend
    volumes:
      - event-frontend:/app
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 80:8000
    networks:
      - doc-net
    # command: npm run start
    depends_on:
      - backend

volumes:
  event-backend:
    driver: local
  event-frontend:
    driver: local

networks:
  doc-net:
    