# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: api2-shobiz-service
spec:
  selector:
    app: api2-shobiz-pod
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
      # port: 443
      # targetPort: 443
  type: LoadBalancer

---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2-shobiz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2-shobiz-pod
      # tier: backend
    # matchExpression:
    #   - {key: app, operator: In, value: [shobiz-pod]}
  template:
    metadata:
      labels:
        app: api2-shobiz-pod
        # tier: backend
    spec:
      containers:
        - name: backend2
          image: prasanti85/nodejs2:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_NODE_SERVER
              value: 'ui-shobiz-service.default'
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"


      

# ---
# # kubectl apply -f=master-deployment.yaml
# # minikube service shobiz-service
# # minikube dashboard
# # kubectl delete -f=master-deployment.yaml
# # kubectl delete deployments,services -l group=example
