# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # port: 443
      # targetPort: 443

---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      # tier: backend
    # matchExpression:
    #   - {key: app, operator: In, value: [shobiz-pod]}
  template:
    metadata:
      labels:
        app: backend
        # tier: backend
    spec:
      containers:
        - name: backend
          image: prasanti85/nodejs:latest
          # imagePullPolicy: Always
          # env:
            # - name: REACT_APP_NODE_SERVER
            #   value: '127.0.0.1:53989'
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

      

# ---
# # kubectl apply -f=master-deployment.yaml
# # minikube service shobiz-service
# # minikube dashboard
# # kubectl delete -f=master-deployment.yaml
# # kubectl delete deployments,services -l group=example
