# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: contacts-service
spec:
  selector:
    app: contacts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
      # port: 443
      # targetPort: 443

---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts
      # tier: backend
    # matchExpression:
    #   - {key: app, operator: In, value: [shobiz-pod]}
  template:
    metadata:
      labels:
        app: contacts
        # tier: backend
    spec:
      containers:
        - name: contacts
          image: prasanti85/nodejs2:latest
          imagePullPolicy: Always
          # env:
            # - name: BACKEND_SERVICE_SERVICE_HOST
              # value: "10.96.92.87"
              # value: "192.168.49.2:31801"
              # value: "backend-service.default"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"


      

# ---
# # kubectl apply -f=master-deployment.yaml
# # minikube service shobiz-service
# # minikube dashboard
# # kubectl delete -f=master-deployment.yaml
# # kubectl delete deployments,services -l group=example
